#!/usr/bin/env python

import sys
import os
import bash_escape

def follow_cmd(f):
	return "less -SR +F --follow-name %s" % (bash_escape.escape(f),)

def main(filenames):
	assert len(filenames) > 0, "please provide at least one file"
	tmux = 'http://gfxmonk.net/dist/0install/tmux-custom.xml'
	command = ['0launch', '-c', tmux, 'new-session', ';']
	for filename in filenames:
		command.extend(['split-window', '-h', follow_cmd(filename), ';'])
	command.extend(['kill-pane', '-t', '0', ';'])
	command.extend(['bind-key', 'q', 'kill-window', '-t', ':0', ';'])
	command.extend(['select-layout', 'even-horizontal'])

	#print repr(command)
	os.execvp("0launch", command)

if __name__ == '__main__':
		main(sys.argv[1:])
		sys.exit(1)

