#!/usr/bin/env python

import sys
import os

def follow_cmd(f):
	if "'" in f:
		raise RuntimeError("Please don't use a file with a single quote character (you know how bash hates that)")
	return "less -SR +F --follow-name '%s'; echo '** Exited: %s **'; cat" % (f,f)

def main(filenames):
	assert len(filenames) > 0, "please provide at least one file"
	tmux = 'http://gfxmonk.net/dist/0install/tmux-custom.xml'
	command = ['0launch', '-c', tmux, 'new-session', ';']
	for filename in filenames:
		command.extend(['split-window', '-h', follow_cmd(filename), ';'])
		command.extend(['select-layout', 'tiled', ';'])
	command.extend(['kill-pane', '-t', '0', ';'])
	command.extend(['select-layout', 'even-horizontal', ';'])
	command.extend(['bind-key', 'q', 'kill-window', '-t', ':0', ';'])
	command.extend(['bind-key', '=', 'select-layout', 'even-horizontal', ';'])

	#print repr(command)
	os.execvp("0launch", command)

if __name__ == '__main__':
		main(sys.argv[1:])
		sys.exit(1)
